# Generated by Django 4.2.2 on 2023-06-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de l’actualité')),
                ('body', models.TextField(max_length=1000, verbose_name='Contenu de l’actualité')),
                ('gambar', models.ImageField(upload_to='blogs_img', verbose_name='Image pour les nouvelles')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
