# Generated by Django 4.2.2 on 2023-06-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblogs',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Cochez pour afficher'),
        ),
        migrations.AlterField(
            model_name='myblogs',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
    ]
